name: Run mypy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install
        run: pip install mypy pydantic

      - name: Install third party stubs
        run: pip install types-requests types-PyYAML types-click types-pkg_resources types-Deprecated

      - name: Install lsst dependencies
        run: |
          pip install -r requirements.txt

      - name: Fake a version
        run: |
          echo "__all__ = ['__version__']" > python/lsst/obs/base/version.py
          echo "__version__ = '0.0.1'" >> python/lsst/obs/base/version.py

      - name: Change to source directory and run mypy
        run: mypy python/lsst
